# Generated by Django 2.2.5 on 2019-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191007_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
