# Generated by Django 2.2.5 on 2019-10-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('is_archive', models.BooleanField(default=False, verbose_name='is_archive')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is_trash')),
                ('is_pin', models.BooleanField(default=False, verbose_name='is_pin')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ManyToManyField(blank=True, related_name='collaborator', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(blank=True, related_name='label', to='Note.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
