# Generated by Django 2.2.5 on 2019-10-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_auto_20191013_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
